name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:      # also allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Summary Cards

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: AadiBiyani
