name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:      # also allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Summary Cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: AadiBiyani
          # Only generate cards for great_gatsby theme to match README
          BRANCH_NAME: "main"
          AUTO_PUSH: false  # We'll handle the commit ourselves
          
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Update GitHub stats [skip ci]"
          git push
